language: php
php:
  - '7.2.22'
  - '7.3.23'
  - '7.4.15'
before_script:
  - mkdir -p /home/travis/build/drosanda/seme-framework/app/cache/
  - chmod 775 /home/travis/build/drosanda/seme-framework/app/cache/
script: phpunit --configuration phpunit.xml --coverage-clover coverage.xml --testsuite Dev
after_success:
    - bash <(curl -s https://codecov.io/bash)
